# Generated by Django 4.1.1 on 2022-09-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('discount_category', models.CharField(choices=[('date', 'Date'), ('time', 'Time')], default='date', max_length=20)),
                ('start_time', models.TimeField(default=None)),
                ('end_time', models.TimeField(default=None)),
                ('start_date', models.DateField(default=None)),
                ('end_date', models.DateField(default=None)),
                ('discount_type', models.CharField(choices=[('flat', 'Flat'), ('percentage', 'Percentage')], default='flat', max_length=10)),
                ('discount_amount', models.IntegerField(default=0)),
            ],
        ),
    ]
