# Generated by Django 4.1.1 on 2022-09-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discount_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountmodel',
            name='end_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='discountmodel',
            name='end_time',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='discountmodel',
            name='start_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='discountmodel',
            name='start_time',
            field=models.TimeField(default=None, null=True),
        ),
    ]
