# Generated by Django 4.1.1 on 2022-09-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discount_App', '0002_alter_discountmodel_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountmodel',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
    ]
