# Generated by Django 4.1.1 on 2022-09-28 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Discount_App', '0003_discountmodel_is_valid'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='discountmodel',
            old_name='product_name',
            new_name='discount_name',
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_category', to='Discount_App.categorymodel')),
                ('disocunt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_discount', to='Discount_App.discountmodel')),
            ],
        ),
    ]
